apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-workload-manager
  namespace: demo
rules:
  - apiGroups: ["", "apps", "argoproj.io"]
    resources:
      - pods
      - pods/log
      - services
      - configmaps
      - deployments
      - replicasets
      - rollouts
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sre-pod-operator
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/exec
      - events
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources:
      - namespaces
      - nodes
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps", "argoproj.io"]
    resources:
      - deployments
      - replicasets
      - rollouts
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-viewer
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
