apiVersion: v1
kind: Pod
metadata:
  name: bad-host-network
  namespace: demo
spec:
  hostNetwork: true
  containers:
    - name: web
      image: nginx:1.27
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
