apiVersion: v1
kind: Pod
metadata:
  name: bad-latest
  namespace: demo
spec:
  containers:
    - name: web
      image: nginx:latest
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
