apiVersion: v1
kind: Pod
metadata:
  name: good-pod
  namespace: demo
  labels:
    owner: platform
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 101
  containers:
    - name: web
      image: nginx:1.27
      securityContext:
        allowPrivilegeEscalation: false
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
